# Statistics utility to count lines of code
brew "cloc"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Remote repository management made easy
brew "ghq"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Git extension for versioning large files
brew "git-lfs"
# Manage your Java environment
brew "jenv"
# Environment diagnostics for Kotlin Multiplatform Mobile app development
brew "kdoctor"
# Simple terminal UI for git commands
brew "lazygit"
# Development kit for the Java programming language
brew "openjdk@17"
# Development kit for the Java programming language
brew "openjdk@21"
# Ruby version manager
brew "rbenv"
# Terminal multiplexer
brew "tmux"
# Kotlin Native Xcode Plugin
brew "xcode-kotlin"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Additional completion definitions for zsh
brew "zsh-completions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
